  services:
    jupyter-notebook:
      image: awong18/heart_disease_group7:56a10cc
      ports:
        - "8888:8888"
      volumes:
        - .:/home/jovyan
      deploy:
        resources:
          limits:
            memory: 5G
      platform: linux/amd64