name: ml_classification_env
channels:
  - conda-forge
  - defaults
dependencies:
  # Python version
  - python=3.9
  
  # Data manipulation and analysis
  - numpy
  - pandas
  
  # Machine learning
  - scikit-learn
  - xgboost
  - lightgbm
  
  # Visualization
  - matplotlib
  - seaborn
  
  # Jupyter Notebook
  - jupyterlab
  
  # Utilities
  - ipykernel
  - ipywidgets
  - tqdm
  
  # Data preprocessing and feature engineering
  - scikit-image  # For image processing tasks if needed
  - imbalanced-learn  # For handling imbalanced datasets
  - category_encoders  # For encoding categorical features
  
  # Additional machine learning libraries (optional)
  - tensorflow  # If deep learning is required
  - pytorch  # If using PyTorch
  
  # Ensure pip is available
  - pip
  
  # Pip-based dependencies (optional)
  - pip:
      - joblib
      - shap  # For interpretability of machine learning models
      - mlxtend  # For additional ML utilities
      - optuna  # For hyperparameter optimization
